import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "scrub-gold":   "#d4c3a1",
        "scrub-dark":   "#2d3436",
        "scrub-grey":   "#636e72",
        "scrub-light":  "#f9f9f9",
        "scrub-accent": "#607d8b",
        "surface-bright": "#f9f9f9",
        "tertiary-fixed": "#e6e2dc",
        "surface-dim": "#dadada",
        "on-secondary-container": "#626361",
        "surface-container": "#eeeeee",
        "outline": "#7d766b",
        "surface-container-high": "#e8e8e8",
        "primary-container": "#d4c3a1",
        "on-primary": "#ffffff",
        "secondary-container": "#e0dfde",
        "inverse-surface": "#2f3131",
        "on-tertiary-container": "#53514d",
        "surface-container-highest": "#e2e2e2",
        "on-primary-fixed-variant": "#51452b",
        "on-primary-container": "#5c5035",
        "on-surface": "#1a1c1c",
        "surface-tint": "#6a5d41",
        "on-secondary-fixed-variant": "#464746",
        "surface": "#f9f9f9",
        "tertiary-fixed-dim": "#c9c6c0",
        "secondary-fixed": "#e3e2e0",
        "tertiary": "#605e5a",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#484742",
        "on-surface-variant": "#4b463d",
        "surface-container-low": "#f3f3f4",
        "primary-fixed-dim": "#d6c5a3",
        "inverse-on-surface": "#f0f1f1",
        "on-secondary": "#ffffff",
        "on-background": "#1a1c1c",
        "on-secondary-fixed": "#1a1c1b",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e2e2e2",
        "primary": "#6a5d41",
        "on-error": "#ffffff",
        "on-primary-fixed": "#231a05",
        "secondary": "#5e5e5d",
        "inverse-primary": "#d6c5a3",
        "background": "#f9f9f9",
        "primary-fixed": "#f3e1bd",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#c7c6c5",
        "outline-variant": "#cec5b9",
        "tertiary-container": "#c8c4be",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#1c1c18",
        "error": "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "24px",
        "section-padding": "120px",
        "unit": "8px",
        "margin-desktop": "80px",
        "gutter": "32px",
        "container-max": "1200px",
      },
      fontFamily: {
        "headline-md": ["EB Garamond", "serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["EB Garamond", "serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["EB Garamond", "serif"],
        "headline-lg-mobile": ["EB Garamond", "serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["28px", { lineHeight: "1.3", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "display-lg": ["56px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
    },
  },
  plugins: [],
};

export default config;
